# Generated by Django 4.2.2 on 2023-08-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/defualt.png", null=True, upload_to=""
            ),
        ),
    ]
